# Generated by Django 4.1 on 2023-04-23 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_scheduler', '0002_offhour_end_date_offhour_start_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offhour',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='offhour',
            name='start_date',
        ),
        migrations.AddField(
            model_name='offhour',
            name='date',
            field=models.DateField(null=True, verbose_name='Enter date'),
        ),
    ]
