# Generated by Django 4.1 on 2023-04-23 06:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meeting_scheduler', '0003_remove_offhour_end_date_remove_offhour_start_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Enter the title of the meeting')),
                ('agenda', models.TextField(verbose_name='Provide agenda of the meeting')),
                ('date', models.DateField(verbose_name='Enter date of the meeting')),
                ('start_time', models.TimeField(verbose_name='Enter start time of the meeting')),
                ('end_time', models.TimeField(verbose_name='Enter end time of the meeting')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest', to=settings.AUTH_USER_MODEL, verbose_name='Select the guest')),
                ('terraformer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Appointment',
                'verbose_name_plural': 'Appointments',
            },
        ),
    ]
