# Generated by Django 4.1 on 2023-04-23 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_scheduler', '0005_alter_appointment_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.BooleanField(null=True, verbose_name='status of the appointment'),
        ),
    ]
